# Pandas와 Numpy


## ndarray : N 차원(Dimension) 배열(Array) 객체

### 1. ndarray 생성 : array()
- 인자로 주로 파이썬 list 또는  ndarray 입력

In [3]:
import numpy as np

# 1차원 배열 생성
array1 = np.array([1, 2, 3])

# 2차원 배열 생성
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(f'array1: \n {array1}\n')
print(f'array2: \n {array2}')

array1: 
 [1 2 3]

array2: 
 [[1 2 3]
 [4 5 6]]


### 2. ndarray 생성 : arrange()
- 0부터 9까지의 숫자를 순차적으로 생성

In [4]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


### 3. ndarray 생성 : zeros() / ones()
- (3, 2) shape을 가지는 모든 원소가 0, dtype은 int32인 ndarray 생성

In [6]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


## 데이터 타입 : ndarray.dtype
- ndarray 내 데이터 타입은 같은 데이터 타입만 가능 -> ndarray.dtype 속성
- 즉, 한 개의 ndarray 객체에 int와 float 함께 불가능 -> astype() 활용하여 형변환

In [7]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


## ndarray의 형태(shape)와 차원(ndim)
- 형태 : ndarray.shape 속성
- 차원 : ndarray.ndim 속성

In [8]:
# (2, 3) shape을 가지는 모든 원소가 1, dtype은 int32인 ndarray 생성
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f'array2: \n {array2}')
print('Shape: ', array2.shape)
print('차원 수 (ndim): ', array2.ndim)

array2: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
차원 수 (ndim):  2


- reshape() : 차원과 크기를 변경
- reshape(-1, N) : 차원과 크기를 변경
  - -1에 해당하는 axis의 크기는 가변적
  - -1이 아닌 인자 값에 해당하는 axis 크기는 인자 값으로 고정하여 shape 변환

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2, 5)
print('array2:\n', array2)

# (5, 2) shape으로 변환
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
# array1.reshape(4, 3)

In [12]:
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

array2 shape: (2, 5)
array3 shape: (5, 2)


## DataFrame과 Numpy/List/딕셔너리 상호 변환
- List -> DataFrame : `list2df = pd.DataFrame(list, columns = col_name)`
- Numpy(ndarray) -> DataFrame : `np2df = pd.DataFrame(ndarray, columns = col_name)`
- Dictionary -> DataFrame : `dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}` / `dict2df = pd.DataFrame(dict)`


# 데이터 처리와 집계

## 객체 생성

In [13]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [14]:
# datatime index를 사용한 객체 생성
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df = pd.DataFrame(np.random.randn(6, 4),  index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01 -0.668313  0.843642 -0.449976 -2.018016
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605
2013-01-04  1.001155  0.242873  0.623869 -0.034941
2013-01-05 -0.987476 -0.590840 -0.581062 -0.237090
2013-01-06 -0.507487 -0.459726  0.449759 -1.333216

In [17]:
df2 = pd.DataFrame(
    {
        'A' : 1.0,
        'B' : pd.Timestamp('20130102'),
        'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
        'D' : np.array([3] * 4, dtype='int32'),
        'E' : pd.Categorical(['test', 'train', 'test', 'train']),
        'F' : 'foo',
    }
)
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [18]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [19]:
df.head()

A         B         C         D
2013-01-01 -0.668313  0.843642 -0.449976 -2.018016
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605
2013-01-04  1.001155  0.242873  0.623869 -0.034941
2013-01-05 -0.987476 -0.590840 -0.581062 -0.237090

In [20]:
df.tail(3)

A         B         C         D
2013-01-04  1.001155  0.242873  0.623869 -0.034941
2013-01-05 -0.987476 -0.590840 -0.581062 -0.237090
2013-01-06 -0.507487 -0.459726  0.449759 -1.333216

In [ ]:
# DataFrame을 numpy로 변환
df.to_numpy()

array([[-0.66831291,  0.84364191, -0.44997581, -2.01801644],
       [ 0.7855027 ,  0.10289862,  0.84978283, -2.33069165],
       [-1.17308008, -0.67460941, -0.5707365 , -0.29260513],
       [ 1.00115533,  0.24287252,  0.6238687 , -0.03494132],
       [-0.98747623, -0.59084033, -0.58106211, -0.23709035],
       [-0.50748701, -0.45972552,  0.4497593 , -1.33321628]])

In [ ]:
# 통계정보 확인
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.258283 -0.089294  0.053606 -1.041094
std    0.924606  0.591440  0.657607  0.992147
min   -1.173080 -0.674609 -0.581062 -2.330692
25%   -0.907685 -0.558062 -0.540546 -1.846816
50%   -0.587900 -0.178413 -0.000108 -0.812911
75%    0.462255  0.207879  0.580341 -0.250969
max    1.001155  0.843642  0.849783 -0.034941

In [23]:
# Transpose 연산
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.668313    0.785503   -1.173080    1.001155   -0.987476   -0.507487
B    0.843642    0.102899   -0.674609    0.242873   -0.590840   -0.459726
C   -0.449976    0.849783   -0.570737    0.623869   -0.581062    0.449759
D   -2.018016   -2.330692   -0.292605   -0.034941   -0.237090   -1.333216

### label을 활용한 데이터의 선택

In [24]:
# DataFrame에서 Series 데이터 추출
df['A']

2013-01-01   -0.668313
2013-01-02    0.785503
2013-01-03   -1.173080
2013-01-04    1.001155
2013-01-05   -0.987476
2013-01-06   -0.507487
Freq: D, Name: A, dtype: float64

In [25]:
# DataFrame에서 slice를 사용해 행들을 추출
df[0:3]

A         B         C         D
2013-01-01 -0.668313  0.843642 -0.449976 -2.018016
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605

In [26]:
df['20130102':'20130104']

A         B         C         D
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605
2013-01-04  1.001155  0.242873  0.623869 -0.034941

In [27]:
# DataFrame에서 slice를 사용해 행들을 추출(label slice)
df.loc['20130102':'20130104', ['A','B']]


A         B
2013-01-02  0.785503  0.102899
2013-01-03 -1.173080 -0.674609
2013-01-04  1.001155  0.242873

In [29]:
# 특정 행과 열에 있는 scalar 값 추출
df.loc[dates[0], 'A']

np.float64(-0.6683129088234564)

### position을 활용한 데이터의 선택

In [30]:
df.iloc[3]

A    1.001155
B    0.242873
C    0.623869
D   -0.034941
Name: 2013-01-04 00:00:00, dtype: float64

In [31]:
df.iloc[3:5, 0:2]

A         B
2013-01-04  1.001155  0.242873
2013-01-05 -0.987476 -0.590840

In [32]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02  0.785503  0.849783
2013-01-03 -1.173080 -0.570737
2013-01-05 -0.987476 -0.581062

In [33]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605

In [34]:
df.iloc[:, 1:3]

B         C
2013-01-01  0.843642 -0.449976
2013-01-02  0.102899  0.849783
2013-01-03 -0.674609 -0.570737
2013-01-04  0.242873  0.623869
2013-01-05 -0.590840 -0.581062
2013-01-06 -0.459726  0.449759

In [35]:
df.iloc[1, 1]

np.float64(0.10289861744682335)

In [36]:
df.iat[1, 1]

np.float64(0.10289861744682335)

### boolean을 활용한 indexing

In [37]:
df[df['A'] > 0]

A         B         C         D
2013-01-02  0.785503  0.102899  0.849783 -2.330692
2013-01-04  1.001155  0.242873  0.623869 -0.034941

In [38]:
df[df > 0]

A         B         C   D
2013-01-01       NaN  0.843642       NaN NaN
2013-01-02  0.785503  0.102899  0.849783 NaN
2013-01-03       NaN       NaN       NaN NaN
2013-01-04  1.001155  0.242873  0.623869 NaN
2013-01-05       NaN       NaN       NaN NaN
2013-01-06       NaN       NaN  0.449759 NaN

In [39]:
df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01 -0.668313  0.843642 -0.449976 -2.018016    one
2013-01-02  0.785503  0.102899  0.849783 -2.330692    one
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605    two
2013-01-04  1.001155  0.242873  0.623869 -0.034941  three
2013-01-05 -0.987476 -0.590840 -0.581062 -0.237090   four
2013-01-06 -0.507487 -0.459726  0.449759 -1.333216  three

In [41]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03 -1.173080 -0.674609 -0.570737 -0.292605   two
2013-01-05 -0.987476 -0.590840 -0.581062 -0.237090  four

#### `sort_values()`
- 오름차순이 기본 (ascending = True)
- 내림차순 정렬 시 ascending  = False 설정

In [42]:
# 이름으로 정렬 (오름차순이 기본)
titanic_df = pd.read_csv('titanic.csv')
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head()

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   

        Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845    male  42.0      0      0  C.A. 5547   7.55   NaN        S  
746    male  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  female  35.0      1      1  C.A. 2673  20.25   NaN        S  
308    male  30.0      1      0  P/PP 3381  24.00   NaN        C  
874  female  28.0      1      0  P/PP 3381  24.00   NaN        C

### `unique()` : 컬럼 내 몇 건의 고유값이 있는지 파악

In [43]:
print(titanic_df['Pclass'].nunique())
print(titanic_df['Survived'].nunique())
print(titanic_df['Name'].nunique())

3
2
891


#### sum() / max() / min() / count()
- DataFrame, Series에서 집계(Aggregation) 수행

In [44]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [45]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [46]:
titanic_df[['Age', 'Fare']].sum()

Age     21205.1700
Fare    28693.9493
dtype: float64

In [47]:
titanic_df[['Age', 'Fare']].min()

Age     0.42
Fare    0.00
dtype: float64

### groupby()

In [50]:
# 동일한 컬럼에 대해 서로 다른 집계함수를 적용하고 싶은 경우 `agg()` 활용
titanic_df.groupby('Pclass')['Age'].max(), titanic_df.groupby('Pclass')['Age'].min()

(Pclass
 1    80.0
 2    70.0
 3    74.0
 Name: Age, dtype: float64,
 Pclass
 1    0.92
 2    0.67
 3    0.42
 Name: Age, dtype: float64)

In [51]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

C:\Users\Bling\AppData\Local\Temp\ipykernel_20704\1565262784.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])
C:\Users\Bling\AppData\Local\Temp\ipykernel_20704\1565262784.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max, min])


max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [52]:
titanic_df.groupby(['Pclass']).agg(age_max = ('Age', 'max'), age_mean = ('Age', 'mean'), fare_mean = ('Fare', 'mean'))

age_max   age_mean  fare_mean
Pclass                               
1          80.0  38.233441  84.154687
2          70.0  29.877630  20.662183
3          74.0  25.140620  13.675550

In [53]:
# 여러 컬럼에 여러 집계함수 적용 시 agg() 내에 딕셔너리 형태로 전달
agg_format = {'Age' : 'max', 'SibSp' : 'sum', 'Fare' : 'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### lambda식 이해

In [54]:
def get_double(a):
    return a * 2

print('3의 두 배는:', get_double(3))

3의 두 배는: 6


In [56]:
lambda_double = lambda x : x * 2
print('3의 두 배는:',lambda_double(3))

3의 두 배는: 6


### `apply()`
- lambda식을 결합하여 데이터를 일괄적으로 가공

In [57]:
# 'Name_len' : 이름의 길이를 일괄 계산하여 추가
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [59]:
# 'Child_Adult' : 나이가 15세 ㅇ이하면 'Child' 그렇지 않은 경우 'Adult'
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x < 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.0       Adult
1  38.0       Adult
2  26.0       Adult
3  35.0       Adult
4  35.0       Adult
5   NaN       Adult
6  54.0       Adult
7   2.0       Child

In [61]:
def categorize_age(age):
    '''
    나이에 따라 연령대를 분류하는 함수
    '''
    if age <= 5:
        return 'Baby'
    elif age <= 12:
        return 'Child'
    elif age <= 18:
        return 'Teenager'
    elif age <= 25:
        return 'Student'
    elif age <= 35:
        return 'Young Adult'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Elderly'

# 'Age' 컬럼의 값을 기반으로 연령대를 분류 후 'Age_cate 컬럼에 저장
# categorize_age(x)는 'Age' 값을 입력받아 해당 연령대 카테고리를 반환함
titanic_df['Age_cate'] = titanic_df['Age'].apply(categorize_age)

# 'Age'와 'Age_cate' 컬럼을 확인
titanic_df[['Age', 'Age_cate']].head()

Age     Age_cate
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

# 데이터 병합 및 변환

In [62]:
# concat
import pandas as pd
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2'],
                    'B' : ['B0', 'B1', 'B2']})

df2 = pd.DataFrame({'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']})

df3 = pd.concat([df1, df2], axis = 0)  # 행 병합
df4 = pd.concat([df1, df2], axis = 1)  # 열 병합

print(df1)
print('\n')
print(df2)
print('\n')
print(df3)
print('\n')
print(df4)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2


    C   D
0  C0  D0
1  C1  D1
2  C2  D2


     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2


    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2


In [63]:
# Inner Merge
df1 = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                    'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how = 'inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3


  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2


  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2


In [64]:
df_merged = pd.merge(df1, df2, on='key', how='outer')

print(df_merged)

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN


In [65]:
df_merged = pd.merge(df1, df2, on='key', how='left')

print(df_merged)

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K2  A2  B2   C2   D2
3  K3  A3  B3  NaN  NaN


In [66]:
df_merged = pd.merge(df1, df2, on='key', how='right')

print(df_merged)

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2


In [68]:
df1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2'],
                    'B' : ['B0', 'B1', 'B2']},
                    index = ['K0', 'K1', 'K2'])

df2 = pd.DataFrame({'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']},
                    index = ['K0', 'K2', 'K3'])

df_merged = df1.join(df2, how='left')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2


     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2


     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1


In [70]:
# Join 실제 예시
sales = pd.DataFrame({'customer_id' : [1, 2, 3, 4],
                       'product_id' : [101, 102, 103, 104],
                       'quantity' : [5, 2, 3, 1]})

customers = pd.DataFrame({'customer_id' : [1, 2, 3, 5],
                          'name' : ['Alice', 'Bob', 'Charlie', 'David'],
                          'city' : ['Seoul', 'Busan', 'Daegu', 'Incheon']})

# 인덱스를 customer_id로 설정
sales = sales.set_index('customer_id')
customers = customers.set_index('customer_id')

# 왼쪽 병합
merged_data = sales.join(customers, how = 'left')

print(sales)
print('\n')
print(customers)
print('\n')
print(merged_data)

             product_id  quantity
customer_id                      
1                   101         5
2                   102         2
3                   103         3
4                   104         1


                name     city
customer_id                  
1              Alice    Seoul
2                Bob    Busan
3            Charlie    Daegu
5              David  Incheon


             product_id  quantity     name   city
customer_id                                      
1                   101         5    Alice  Seoul
2                   102         2      Bob  Busan
3                   103         3  Charlie  Daegu
4                   104         1      NaN    NaN


In [71]:
# 열 이름 변경
df1 = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                    'A' : ['A0', 'A1', 'A2', 'A3'],
                    'C' : ['C0', 'C1', 'C2', 'C3']})  # 'C' 열 추가

df2 = pd.DataFrame({'key' : ['K0', 'K1', 'K2'],
                    'C' : ['C4', 'C5', 'C6'],  # 'C' 열 중복
                    'D' : ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='inner', suffixes=('_left', '_right'))

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key   A   C
0  K0  A0  C0
1  K1  A1  C1
2  K2  A2  C2
3  K3  A3  C3


  key   C   D
0  K0  C4  D0
1  K1  C5  D1
2  K2  C6  D2


  key   A C_left C_right   D
0  K0  A0     C0      C4  D0
1  K1  A1     C1      C5  D1
2  K2  A2     C2      C6  D2


In [72]:
df1 = pd.DataFrame({'key' : ['K0', 'K1', 'K2', 'K3'],
                    'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key' : ['K0', 'K1', 'K2'],
                    'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on = 'key', how ='inner')
df_merged = df_merged.drop('B', axis=1)
print(df_merged)

  key   A   C   D
0  K0  A0  C0  D0
1  K1  A1  C1  D1
2  K2  A2  C2  D2


In [73]:
df1 = pd.DataFrame({'key1' : ['K0', 'K1', 'K2', 'K3'],
                    'key2' : ['K4', 'K5', 'K6', 'K7'],
                    'A' : ['A0', 'A1', 'A2', 'A3'],
                    'B' : ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key1' : ['K0', 'K1', 'K2'],
                    'key2' : ['K4', 'K5', 'K6'],
                    'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on = ['key1', 'key2'], how = 'inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)

  key1 key2   A   B
0   K0   K4  A0  B0
1   K1   K5  A1  B1
2   K2   K6  A2  B2
3   K3   K7  A3  B3


  key1 key2   C   D
0   K0   K4  C0  D0
1   K1   K5  C1  D1
2   K2   K6  C2  D2


  key1 key2   A   B   C   D
0   K0   K4  A0  B0  C0  D0
1   K1   K5  A1  B1  C1  D1
2   K2   K6  A2  B2  C2  D2


In [76]:
# 데이터의 변환 : replace()
## 원본 값을 특정 값으로 대체
titanic_test_df = titanic_df.copy()
titanic_test_df['Sex'] = titanic_test_df['Sex'].replace({'male':'Man', 'female':'Woman'})
titanic_test_df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name    Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    Man  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  Woman  38.0      1   
2                             Heikkinen, Miss. Laina  Woman  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  Woman  35.0      1   
4                           Allen, Mr. William Henry    Man  35.0      0   
5                                   Moran, Mr. James    Man   NaN      0   
6                            McCarthy, Mr. Timothy J    Man  54.0      0   
7                     Palsson, Master. Gosta Leonard    Man   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  Woman  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  Woman  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  Name_len Child_Adult  \
0      0         A/5 21171   7.2500   NaN        S        23       Adult   
1      0          PC 17599  71.2833   C85        C        51       Adult   
2      0  STON/O2. 3101282   7.9250   NaN        S        22       Adult   
3      0            113803  53.1000  C123        S        44       Adult   
4      0            373450   8.0500   NaN        S        24       Adult   
5      0            330877   8.4583   NaN        Q        16       Adult   
6      0             17463  51.8625   E46        S        23       Adult   
7      1            349909  21.0750   NaN        S        30       Child   
8      2            347742  11.1333   NaN        S        49       Adult   
9      0            237736  30.0708   NaN        C        35       Child   

      Age_cate  
0      Student  
1        Adult  
2  Young Adult  
3  Young Adult  
4  Young Adult  
5      Elderly  
6        Adult  
7         Baby  
8  Young Adult  
9     Teenager

In [77]:
# 결측값 처리시에도 사용
titanic_test_df['Cabin'] = titanic_test_df['Cabin'].replace(np.nan, 'CXXX')
titanic_test_df['Cabin'].value_counts(dropna=False)

Cabin
CXXX           687
G6               4
C23 C25 C27      4
B96 B98          4
F2               3
              ... 
E17              1
A24              1
C50              1
B42              1
C148             1
Name: count, Length: 148, dtype: int64